# **Lab: Model Serving**

## Exercise 1: EDA and Baseline Model

In this exercise we will start our data science project by preparing the dataset for modeling.

The steps are:
1.   Setup Environment
2.   Load and explore dataset
3.   Split Dataset
4.   Get Baseline model
5.   Push changes

## 0. Pre-Requisites

- Created a folder structure following Cookiecutter Data Science template
- Initialise a Git repository linked to Github and created a dedicated branch
- Install required Python dependencies with uv
- Launched Jupyter Lab using uv

### 1. Setup Environment

**[1.1]** Download the dataset into the sub-folder data/raw (https://github.com/aso-uts/labs_datasets/raw/main/36120-adv_mla/lab03/archive.zip)

In [ ]:
# For Windows users, you can download and install WGET. Or you can manually download the file from the link and save it to specified path
! wget -P ~/Projects/adv_mla_2026/adv_mla_lab_3/data/raw https://github.com/aso-uts/labs_datasets/raw/main/36120-adv_mla/lab03/archive.zip

**[1.2]** Navigate the folder `notebooks` and create a new jupyter notebook called `1_baseline.ipynb`

### 2.   Load and Explore Dataset

**[2.1]** Launch magic commands to automatically reload modules

In [1]:
%load_ext autoreload
%autoreload 2

**[2.2]** Import the pandas and numpy packages

In [2]:
import pandas as pd
import numpy as np

**[2.3]** Load the dataset into a dataframe called `df`

In [3]:
import os
import pandas as pd

# Load the dataset using the absolute path where it was downloaded
file_path = os.path.expanduser("~/Projects/adv_mla_2026/adv_mla_lab_3/data/raw/CVD_cleaned.csv")
df = pd.read_csv(file_path)

# Verify the data loaded correctly
df.head()

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0

**[2.4]** Display the first 5 rows of `df`

In [4]:
df.head(5)

,General_Health,Checkup,Exercise,Heart_Disease,Skin_Cancer,Other_Cancer,Depression,Diabetes,Arthritis,Sex,Age_Category,Height_(cm),Weight_(kg),BMI,Smoking_History,Alcohol_Consumption,Fruit_Consumption,Green_Vegetables_Consumption,FriedPotato_Consumption
0,Poor,Within the past 2 years,No,No,No,No,No,No,Yes,Female,70-74,150.0,32.66,14.54,Yes,0.0,30.0,16.0,12.0
1,Very Good,Within the past year,No,Yes,No,No,No,Yes,No,Female,70-74,165.0,77.11,28.29,No,0.0,30.0,0.0,4.0
2,Very Good,Within the past year,Yes,No,No,No,No,Yes,No,Female,60-64,163.0,88.45,33.47,No,4.0,12.0,3.0,16.0
3,Poor,Within the past year,Yes,Yes,No,No,No,Yes,No,Male,75-79,180.0,93.44,28.73,No,0.0,30.0,30.0,8.0
4,Good,Within the past year,No,No,No,No,No,No,No,Male,80+,191.0,88.45,24.37,Yes,0.0,8.0,4.0,0.0

**[2.5]** Display the dimensions of `df`

In [5]:
df.shape

(308854, 19)

**[2.6]** Display the summary (info) of `df`

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308854 entries, 0 to 308853
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   General_Health                308854 non-null  object
 1   Checkup                       308854 non-null  object
 2   Exercise                      308854 non-null  object
 3   Heart_Disease                 308854 non-null  object
 4   Skin_Cancer                   308854 non-null  object
 5   Other_Cancer                  308854 non-null  object
 6   Depression                    308854 non-null  object
 7   Diabetes                      308854 non-null  object
 8   Arthritis                     308854 non-null  object
 9   Sex                           308854 non-null  object
 10  Age_Category                  308854 non-null  object
 11  Height_(cm)                   308854 non-null  float64
 12  Weight_(kg)                   308854 non-null  float64
 13  BMI                           308854 non-null  float64
 14  Smoking_History               308854 non-null  object
 15  Alcohol_Consumption           308854 non-null  float64
 16  Fruit_Consumption             308854 non-null  float64
 17  Green_Vegetables_Consumption  308854 non-null  float64
 18  FriedPotato_Consumption       308854 non-null  float64
dtypes: float64(7), object(12)
memory usage: 44.8+ MB

**[2.7]** Display the descriptive statistics of `df`

In [9]:
df.describe

<bound method NDFrame.describe of        General_Health                  Checkup Exercise Heart_Disease  \
0                Poor  Within the past 2 years       No            No
1           Very Good     Within the past year       No           Yes
2           Very Good     Within the past year      Yes            No
3                Poor     Within the past year      Yes           Yes
4                Good     Within the past year       No            No
...               ...                      ...      ...           ...
308849      Very Good     Within the past year      Yes            No
308850           Fair  Within the past 5 years      Yes            No
308851      Very Good      5 or more years ago      Yes            No
308852      Very Good     Within the past year      Yes            No
308853      Excellent     Within the past year      Yes            No

       Skin_Cancer Other_Cancer Depression  \
0               No           No         No
1               No           No         No
2               No           No         No
3               No           No         No
4               No           No         No
...            ...          ...        ...
308849          No           No         No
308850          No           No         No
308851          No           No        Yes
308852          No           No         No
308853          No           No         No

                                          Diabetes Arthritis     Sex  \
0                                               No       Yes  Female
1                                              Yes        No  Female
2                                              Yes        No  Female
3                                              Yes        No    Male
4                                               No        No    Male
...                                            ...       ...     ...
308849                                          No        No    Male
308850                                         Yes        No    Male
308851  Yes, but female told only during pregnancy        No  Female
308852                                          No        No    Male
308853                                          No        No  Female

       Age_Category  Height_(cm)  Weight_(kg)    BMI Smoking_History  \
0             70-74        150.0        32.66  14.54             Yes
1             70-74        165.0        77.11  28.29              No
2             60-64        163.0        88.45  33.47              No
3             75-79        180.0        93.44  28.73              No
4               80+        191.0        88.45  24.37             Yes
...             ...          ...          ...    ...             ...
308849        25-29        168.0        81.65  29.05              No
308850        65-69        180.0        69.85  21.48              No
308851        30-34        157.0        61.23  24.69             Yes
308852        65-69        183.0        79.38  23.73              No
308853        45-49        160.0        81.19  31.71              No

        Alcohol_Consumption  Fruit_Consumption  Green_Vegetables_Consumption  \
0                       0.0               30.0                          16.0
1                       0.0               30.0                           0.0
2                       4.0               12.0                           3.0
3                       0.0               30.0                          30.0
4                       0.0                8.0                           4.0
...                     ...                ...                           ...
308849                  4.0               30.0                           8.0
308850                  8.0               15.0                          60.0
308851                  4.0               40.0                           8.0
308852                  3.0               30.0                          12.0
308853                  1.0                5.0                          12.0

        FriedPotato_Consumption
0                          12.0
1                           4.0
2                          16.0
3                           8.0
4                           0.0
...                         ...
308849                      0.0
308850                      4.0
308851                      4.0
308852                      0.0
308853                      1.0

[308854 rows x 19 columns]>

### 3. Split Dataset

**[3.1]** Create a copy of `df` and save it into a variable called `df_cleaned`

In [ ]:
# Placeholder for student's code (Python code)

**[3.2]** Convert the values of `Heart_Disease` into numerical type and save the results in a variable called `target`

In [ ]:
# Placeholder for student's code (Python code)

**[3.3]** Import the function `split_sets_random` from your custom package and split the data into several sets as Numpy arrays

In [ ]:
# Placeholder for student's code (Python code)

**[3.4]** Import the function `save_sets` from your custom package and save the sets into the folder `data/processed`

In [ ]:
# Placeholder for student's code (Python code)

### 4. Baseline Model

**[4.1]** Import the DummyClassifier module from sklearn

In [ ]:
from sklearn.dummy import DummyClassifier

**[4.2]** Instantiate a `DummyClassifier` and save it into a variable called `base_model`

In [ ]:
base_model = DummyClassifier(strategy='most_frequent')

**[4.3]** Make a prediction using `fit_predict()` and save the results in a variable called `y_base`

In [ ]:
y_base = base_model.fit(X_train, y_train).predict(X_train)

**[4.4]** Import the function `print_classifier_scores` from your custom package and display the Accuracy and F1 scores of this baseline model on the training set

In [ ]:
from lab3 import print_classifier_scores

print_classifier_scores(y_train, y_base, set_name="Training")

### 5.   Push changes

**[5.1]** Add you changes to git staging area

In [ ]:
!git add notebooks/baseline.ipynb lab3/dataset.py lab3/__init__.py

**[5.2]** Create the snapshot of your repository and add a description

In [ ]:
!git commit -m "Implement data split, baseline model, and helper functions"

**[5.3]** Push your snapshot to Github

In [ ]:
!git push origin main

**[5.4]** Go to Github and merge the branch after reviewing the code and fixing any conflict

**[5.5]** Check out to the master branch

In [ ]:
!git checkout main

**[5.6]** Pull the latest updates

In [ ]:
!git pull